name: Build and test pull request

on: [pull_request]

jobs:
  Windows:
    name: Build windows version
    runs-on: windows-2019
    timeout-minutes: 90

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild

    - name: Setup vcpkg
      shell: pwsh
      run: |
        $env:VCPKG_ROOT = "${{ github.workspace }}\vcpkg"
        git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
        Set-Location $env:VCPKG_ROOT
        git checkout 3b3bd424827a1f7f4813216f6b32b6c61e386b2e
        .\bootstrap-vcpkg.bat

    - name: Install dependencies via vcpkg
      run: |
        $env:VCPKG_ROOT = "${{ github.workspace }}\vcpkg"
        $env:VCPKG_DEFAULT_TRIPLET = "x86-windows-static"
        $env:PATH += ";$env:VCPKG_ROOT"
        Set-Location ${{ github.workspace }}  # Asegúrate de estar en la carpeta principal del proyecto
        & "$env:VCPKG_ROOT\vcpkg.exe" install --triplet x86-windows-static

    - name: Integrate vcpkg
      run: |
        ${{ github.workspace }}/vcpkg/vcpkg integrate install

    - name: Compile otclient_dx
      timeout-minutes: 20
      run: |
        cd vc17
        MSBuild /property:Configuration=DirectX /p:BUILD_REVISION=${{github.run_number}}

    - name: Compile otclient_gl
      timeout-minutes: 20
      run: |
        cd vc17
        MSBuild /property:Configuration=OpenGL /p:BUILD_REVISION=${{github.run_number}}

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: Binaries
        path: |
          otclient_gl.exe
          otclient_dx.exe
          lib.7z
        if-no-files-found: error
