name: Build on request
on: [workflow_dispatch]

jobs:
  Windows:
    name: Build windows version
    runs-on: windows-2019
    timeout-minutes: 120

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild

    - name: Setup vcpkg
      shell: pwsh
      run: |
        $env:VCPKG_ROOT = "${{ github.workspace }}\vcpkg"
        git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
        Set-Location $env:VCPKG_ROOT
        .\bootstrap-vcpkg.bat

    - name: Install dependencies via vcpkg
      shell: pwsh
      run: |
        $env:VCPKG_ROOT = "${{ github.workspace }}\vcpkg"
        $env:VCPKG_DEFAULT_TRIPLET = "x86-windows-static"
        Set-Location $env:VCPKG_ROOT
        .\vcpkg.exe install

    - name: Integrate vcpkg
      run: |
        ${{ github.workspace }}/vcpkg/vcpkg integrate install
        
    - name: Compile otclient_dx Win32
      timeout-minutes: 20
      run: |
        cd vc17
        MSBuild /property:Configuration=DirectX /p:Platform=Win32 /p:BUILD_REVISION=${{github.run_number}}

    - name: Compile otclient_gl Win32
      timeout-minutes: 20
      run: |
        cd vc17
        MSBuild /property:Configuration=OpenGL /p:Platform=Win32 /p:BUILD_REVISION=${{github.run_number}}

    #- name: Sign binaries
    #  run: |
    #     .\tools\sign\signtool.exe sign /f .\tools\sign\certificate.pfx /p ${{ secrets.SIGN_PASSWORD }} /fd SHA256 /t http://timestamp.digicert.com /d "OTclientV8" otclient_gl.exe
    #     .\tools\sign\signtool.exe sign /f .\tools\sign\certificate.pfx /p ${{ secrets.SIGN_PASSWORD }} /fd SHA256 /t http://timestamp.digicert.com /d "OTclientV8" otclient_dx.exe

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: Download-binaries
        path: |
          vc17\Win32\DirectX\otclient_dx.exe
          vc17\Win32\OpenGL\otclient_gl.exe
        if-no-files-found: error
