name: Build and test pull request

on: [pull_request]

jobs:
  Windows:
    name: Build windows version
    runs-on: windows-2019
    timeout-minutes: 90

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild

    - name: Setup vcpkg
      shell: pwsh
      run: |
        $env:VCPKG_ROOT = "${{ github.workspace }}\vcpkg"
        git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
        Set-Location $env:VCPKG_ROOT
        git checkout 3b3bd424827a1f7f4813216f6b32b6c61e386b2e
        .\bootstrap-vcpkg.bat

    - name: Install dependencies via vcpkg
      shell: pwsh
      run: |
        $env:VCPKG_ROOT = "${{ github.workspace }}\vcpkg"
        $env:VCPKG_DEFAULT_TRIPLET = "x86-windows-static"
        $env:PATH += ";$env:VCPKG_ROOT"

        & "$env:VCPKG_ROOT\vcpkg.exe" install `
          boost-iostreams `
          boost-asio `
          boost-beast `
          boost-system `
          boost-variant `
          boost-lockfree `
          boost-process `
          boost-program-options `
          boost-uuid `
          boost-filesystem `
          luajit `
          glew `
          physfs `
          openal-soft `
          libogg `
          libvorbis `
          zlib `
          libzip `
          bzip2 `
          openssl `
          liblzma

    - name: Compile
      shell: pwsh
      timeout-minutes: 60
      run: |
        Set-Location vc17
        MSBuild otclient.sln /m /p:Configuration=DirectX /p:PlatformToolset=v142 /p:BUILD_REVISION=${{ github.run_number }}
        MSBuild otclient.sln /m /p:Configuration=OpenGL /p:PlatformToolset=v142 /p:BUILD_REVISION=${{ github.run_number }}

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: Binaries
        path: |
          otclient_gl.exe
          otclient_dx.exe
          lib.7z
        if-no-files-found: error
